### ISSUE TITLE
did you forget make tags or releases ?

### ISSUE THREAD

**Issue by sergiomb2** [SergeySatskiy/codimension#445]
in what version we are ? I saw 

codimension_2.3.1-0%7Eppa1%7Eutopic1.dsc      
codimension-parser_1.6.8-0%7Eppa1%7Eutopic1.dsc

**Comment by SergeySatskiy** [comment]
I am sorry for a late answer - github did not notify me about the issue or, perhaps, I missed it.
Long story short, the currently publicly available versions are 2.3.1 for the IDE and 1.6.8 for the parser (http://satsky.spb.ru/codimension/installationEng.php). However they are totally obsolete. The project is in a painful process of repackaging. Here is a brief description of what will be available and what is done:
- instead of launchpad packages there will be github packages
- the code is split into 3 repositories:
-- content parser (https://github.com/SergeySatskiy/cdm-pythonparser)
-- control flow parser (https://github.com/SergeySatskiy/cdm-flowparser)
-- IDE with plugins (https://github.com/SergeySatskiy/codimension)
The content parser has been reworked completely and became both smaller and faster. The packages for 4 platforms are available right now.
The flow parser is new and is used for diagram generation. The packages for 4 platforms are available right now.
The IDE now supports control flow diagram generation on-the-fly for an arbitrary python code. The packaging of the new version is in process and took more than 8 months by now. I still cannot say when it is going to be ready. Someone helps me with packaging but it is not a commercial project so there is nothing like a deadline. When the packaging is done, the release will be available via github.

Also there will be a project website codimension.org. It will have all the project information including documentation. The site content is ready but it will be opened for public when the IDE package is ready.

Sorry for inconvenience,
Sergey

**Comment by sergiomb2** [comment]
Hi, no problem at all, . my  account was flagged , it was unflagged yesterday , so maybe unflagged trigger this .
Anyway the question is IIUC  version mention have more than 2 years, so if you do some tags , could be easy to package and we will have more unified tests . 
I see that we have pack cdm-pythonparser and cdm-flowparser , now we just need to know what is the version of codimension :smiley:  ,  pkg/codimension-parser-1.6.suse.spec is already there

**Comment by SergeySatskiy** [comment]
Sergio,
we finally finished the packages preparation.
To have the IDE installed three packages are required:
- python parser (https://github.com/SergeySatskiy/cdm-pythonparser), latest version 2.0.1
- control flow parser (https://github.com/SergeySatskiy/cdm-flowparser), latest version 1.0.1
- Codimension IDE (https://github.com/SergeySatskiy/codimension), latest version 3.0.0
spec files for each of the package are in the appropriate repositories.

It took time to polish the packages and removing confusions but now everything looks clean. Sorry for the delay.

Are you planning to push Codimension to Fedora?

**Comment by sergiomb2** [comment]
> Are you planning to push Codimension to Fedora?

:smile:, I'm not planing that,  I'm looking a good python IDE, that I like to use. If I use it often, I may think in packaging in official repos. 
Before we can build it and  test it on https://copr.fedorainfracloud.org
Unfortunately I have a lot of open source projects , so I shouldn't have much time . But for now I'd like to test it, soon, anyway versioning is a good step to be packaged .
Thanks for your reply

**Comment by SergeySatskiy** [comment]
I see.
Thanks for your interest then.
